[title] update source code about weather app  (JS, HTML and CSS)
MinhTuan2405/MOSO_gitPractise pull request #1
Opened 2024-08-30 18:44 UTC by MinhTuan2405

update 1: 
create the frame HTML for the weather app - change in the index.HTML  file

update 2:
create the style for the weather app - change in the main.css file

update 3: 
update the logic for the weather app - change in the script.js file, add a feature to watch the weather in the entered location

2024-08-31 08:22 UTC, thangphanmoso requested changes
em xem lại PR creation guideline và update nha. a thấy PR title & PR description chưa rõ ràng, chưa nêu ra được PR này thay đổi gì

2024-08-31 08:22 UTC, thangphanmoso commented on index.html
CS5.2: em bổ sung thêm comment cho từng block/section trong file này nhe. ví dụ
```
// styles
<link ref="stylesheet"...
```

```
// search box
<div class="search-box">
            <i class="fa-solid fa-location-dot"></i>
            <input type="text" placeholder="enter location">
            <button class="fa-solid fa-magnifying-glass"></button>
        </div>   
```

2024-08-31 08:22 UTC, thangphanmoso commented on script.js
CS5.2: em bổ sung thêm comment cho file này nhe

2024-08-31 08:24 UTC, MinhTuan2405 commented
Dạ vâng anh

Vào 15:22, Th 7, 31 thg 8, 2024 Thang Phan ***@***.***> đã
viết:

> ***@***.**** requested changes on this pull request.
>
> em xem lại PR creation guideline và update nha. a thấy PR title & PR
> description chưa rõ ràng, chưa nêu ra được PR này thay đổi gì
> ------------------------------
>
> On index.html
> <https://github.com/MinhTuan2405/MOSO_gitPractise/pull/1#discussion_r1739637640>
> :
>
> CS5.2: em bổ sung thêm comment cho từng block/section trong file này nhe.
> ví dụ
>
> // styles
> <link ref="stylesheet"...
>
> // search box
> <div class="search-box">
>             <i class="fa-solid fa-location-dot"></i>
>             <input type="text" placeholder="enter location">
>             <button class="fa-solid fa-magnifying-glass"></button>
>         </div>
>
> ------------------------------
>
> On script.js
> <https://github.com/MinhTuan2405/MOSO_gitPractise/pull/1#discussion_r1739637693>
> :
>
> CS5.2: em bổ sung thêm comment cho file này nhe
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MinhTuan2405/MOSO_gitPractise/pull/1#pullrequestreview-2273788171>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV42EJRY2PPNRVAXI2PN27LZUF4M3AVCNFSM6AAAAABNM7F3V6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENZTG44DQMJXGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-31 14:43 UTC, MinhTuan2405 commented
> em xem lại PR creation guideline và update nha. a thấy PR title & PR description chưa rõ ràng, chưa nêu ra được PR này thay đổi gì

em update PR title và description rồi a

2024-09-04 16:49 UTC, merged

2024-09-05 00:37 UTC, thangphanmoso commented
@MinhTuan2405 em nên request a review lại và được approve trước khi merge PR nhe

2024-09-05 01:33 UTC, MinhTuan2405 commented
em hiểu rồi ạ, để em làm lại một PR mới sửa lại

Vào Th 5, 5 thg 9, 2024 vào lúc 07:38 Thang Phan ***@***.***>
đã viết:

> @MinhTuan2405 <https://github.com/MinhTuan2405> em nên request a review
> lại và được approve trước khi merge PR nhe
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MinhTuan2405/MOSO_gitPractise/pull/1#issuecomment-2330379900>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV42EJRLVJC2SRATOBVG6L3ZU6RWZAVCNFSM6AAAAABNM7F3V6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMZQGM3TSOJQGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-05 16:54 UTC, thangphanmoso commented
@MinhTuan2405 em revert merged PR và reopen là ok 
![image](https://github.com/user-attachments/assets/69d37ed6-5526-4ae8-8736-66062c9a7e54)

2024-09-05 17:26 UTC, MinhTuan2405 commented
em reopen lại được rồi, em tưởng xóa là sẽ mất luôn branch đó chứ


Vào Th 5, 5 thg 9, 2024 vào lúc 23:54 Thang Phan ***@***.***>
đã viết:

> @MinhTuan2405 <https://github.com/MinhTuan2405> em revert merged PR và
> reopen là ok
> image.png (view on web)
> <https://github.com/user-attachments/assets/69d37ed6-5526-4ae8-8736-66062c9a7e54>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MinhTuan2405/MOSO_gitPractise/pull/1#issuecomment-2332215958>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV42EJU5HR7I2CNAWDYWXODZVCEETAVCNFSM6AAAAABNM7F3V6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMZSGIYTKOJVHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>